### ISSUE TITLE
CSS assets fail to load via SSL in Chrome with MIXED_CONTENT error

### ISSUE THREAD

**Issue by mattaudesse** [lwm/lwm.github.io#19]
Hi Luke,

I see the following in my Chrome console when browsing your site (note that I have the "HTTPS Everywhere" plugin activated, so without manual intervention I'm forced by default to use HTTPS URIs).

 
```
Mixed Content: The page at 'https://lwm.github.io/static-analysis-with-haskell/' was loaded over HTTPS, but requested an insecure stylesheet 'http://lwm.github.io/static/css/main.css'.
This request has been blocked; the content must be served over HTTPS.
lwm.github.io/:7

Mixed Content: The page at 'https://lwm.github.io/static-analysis-with-haskell/' was loaded over HTTPS, but requested an insecure stylesheet 'http://lwm.github.io/static/css/pygment.css'.
This request has been blocked; the content must be served over HTTPS.
lwm.github.io/:1

Mixed Content: The page at 'https://lwm.github.io/static-analysis-with-haskell/' was loaded over HTTPS, but requested an insecure stylesheet 'http://lwm.github.io/static/css/main.css'.
This request has been blocked; the content must be served over HTTPS.
lwm.github.io/:1

Mixed Content: The page at 'https://lwm.github.io/static-analysis-with-haskell/' was loaded over HTTPS, but requested an insecure stylesheet 'http://lwm.github.io/static/css/pygment.css'.
This request has been blocked; the content must be served over HTTPS.
```

You could probably just replace `'http://lwm.github.io/static/css/<asset-name>.css'` with `'//lwm.github.io/static/css/<asset-name>.css'` in your source, yeah?

**Comment by lwm** [comment]
Ah yes, most likely, I will try your suggestion! Thank you very much for the report!!!

I fully approve of the "HTTPS Everywhere" plugin :+1:

**Comment by mattaudesse** [comment]
No problem - thanks and good luck!

**Comment by lwm** [comment]
Does that work @mattaudesse? Just deployed a new version.

**Comment by mattaudesse** [comment]
Yup, looks great.

I like the site's styles a lot BTW - only slightly more retro than the stark white pages I saw with no active styling at all!

**Comment by lwm** [comment]
> I like the site's styles a lot BTW - only slightly more retro than the stark white pages I saw with no active styling at all!

:smile: 

Thanks!
