### ISSUE TITLE
Help finding old content

### ISSUE THREAD

**Issue by tfausak** [lwm/lwm.github.io#20]
I was checking [Haskell Weekly](https://haskellweekly.news) for broken links and came across a few from your blog. Can you help me find this old post? http://lwm.github.io/posts/html/document-haskell.html

**Comment by lwm** [comment]
Hey! That's cool your are doing some spring cleaning but I'm pretty sure I lost that post along the way with (re)doing a new blog. Which is a shame really. Anyway, thanks and keep up the good work with Haskell Weekly :)

**Comment by tfausak** [comment]
I managed to find the post on the Internet Archive: https://web.archive.org/web/20160808155551/http://lwm.github.io:80/posts/html/document-haskell.html

If you feel like re-hosting it some place that would be great. Otherwise I'll update my link to point to the archive.

**Comment by lwm** [comment]
Oh, that's really great, nice one! Let me get this hosted again ...

**Comment by lwm** [comment]
OK, back in business -https://lwm.github.io/lets-write-documentation-for-haskell/

:beers: 

Thanks :)

**Comment by tfausak** [comment]
:tada: Thanks!
